### ISSUE TITLE
living-room-js specific sensor/vis readme doc should be in living-room-js repo

### ISSUE THREAD

**Issue by jedahan** [jedahan/living-room#25]
we can link to 'how do i share data from a sensor' and 'how do i make a visualization' from the current repo,

**Comment by geoffreylitt** [comment]
As we talked about today, would also be nice to link to the color sensor code from this repo

**Comment by jedahan** [comment]
I added the colorTracker to the jedahan/living-room-sensors repo as a submodule for now

still not sure if we should move stuff from this main repo to the -js repo or not, especially since its the canonical way people would get involved

**Comment by jedahan** [comment]
I added the colorTracker to the jedahan/living-room-sensors repo as a submodule for now

still not sure if we should move stuff from this main repo to the -js repo or not, especially since its the canonical way people would get involved

**Comment by jedahan** [comment]
moved
