### ISSUE TITLE
Failed to recurse into submodule path 'living-room-sensors'

### ISSUE THREAD

**Issue by sssoleileraaa** [jedahan/living-room#39]
I'm on OS X 10.13.3. I get an error when I try to clone your repo and its submodules.
```
» git clone --recursive https://github.com/jedahan/living-room.git
...
error: Server does not allow request for unadvertised object d24453b4725a15b8838fdd290c93b53fbc10ba50
Fetched in submodule path 'living-room-sensors/colorTracker', but it did not contain d24453b4725a15b8838fdd290c93b53fbc10ba50. Direct fetching of that commit failed.
Submodule path 'living-room-server': checked out '9f8f9f3e30af499d82dde51588e93395dccbc917'
Failed to recurse into submodule path 'living-room-sensors'
```

**Comment by sssoleileraaa** [comment]
Well, looks like the error went away when I removed the directory and did another recursive clone. Huh. I'll close the issue.

**Comment by jedahan** [comment]
oops, I forgot to push that commit d24453b4725a15b8838fdd290c93b53fbc10ba50 in colorTracker, so living-room-sensors was pointing to d24453b4725a15b8838fdd290c93b53fbc10ba50 but github didnt have it. Try again?
